package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import chat.ChatInterface;
import chat.Message;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;

/**
 *
 * @author andy0
 */
public class ChatView extends javax.swing.JFrame implements MouseListener, KeyListener {

    String username;
    ChatInterface chat;
    List<Message> msgs = new ArrayList<>();
    List<String> users = new ArrayList<>();

    /**
     * Creates new form ChatView
     */
    public ChatView(ChatInterface chat, String username) throws RemoteException {
        initComponents();
        this.chat = chat;
        this.username = username;
        chat.login(username);
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        userListTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        chatInputText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatListTextArea = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        userListTextArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        i1 = new javax.swing.JLabel();
        i0 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        i3 = new javax.swing.JLabel();
        i4 = new javax.swing.JLabel();
        i5 = new javax.swing.JLabel();
        i6 = new javax.swing.JLabel();
        i7 = new javax.swing.JLabel();
        i8 = new javax.swing.JLabel();
        i9 = new javax.swing.JLabel();
        i10 = new javax.swing.JLabel();
        i11 = new javax.swing.JLabel();
        i12 = new javax.swing.JLabel();
        i13 = new javax.swing.JLabel();
        i14 = new javax.swing.JLabel();
        i15 = new javax.swing.JLabel();
        i16 = new javax.swing.JLabel();
        i17 = new javax.swing.JLabel();
        i18 = new javax.swing.JLabel();
        i19 = new javax.swing.JLabel();
        i20 = new javax.swing.JLabel();
        i21 = new javax.swing.JLabel();
        i22 = new javax.swing.JLabel();
        i23 = new javax.swing.JLabel();
        i24 = new javax.swing.JLabel();
        i25 = new javax.swing.JLabel();
        i26 = new javax.swing.JLabel();
        i27 = new javax.swing.JLabel();
        i28 = new javax.swing.JLabel();
        i29 = new javax.swing.JLabel();
        i30 = new javax.swing.JLabel();
        i31 = new javax.swing.JLabel();
        i32 = new javax.swing.JLabel();
        i33 = new javax.swing.JLabel();
        i34 = new javax.swing.JLabel();
        i35 = new javax.swing.JLabel();
        i36 = new javax.swing.JLabel();
        i37 = new javax.swing.JLabel();
        i38 = new javax.swing.JLabel();
        i39 = new javax.swing.JLabel();
        i40 = new javax.swing.JLabel();
        i41 = new javax.swing.JLabel();
        i42 = new javax.swing.JLabel();
        i43 = new javax.swing.JLabel();
        i44 = new javax.swing.JLabel();
        i45 = new javax.swing.JLabel();
        i46 = new javax.swing.JLabel();
        i47 = new javax.swing.JLabel();
        i48 = new javax.swing.JLabel();
        i49 = new javax.swing.JLabel();
        i50 = new javax.swing.JLabel();
        i51 = new javax.swing.JLabel();
        i52 = new javax.swing.JLabel();
        i53 = new javax.swing.JLabel();
        i54 = new javax.swing.JLabel();
        i55 = new javax.swing.JLabel();
        i56 = new javax.swing.JLabel();
        i57 = new javax.swing.JLabel();
        i58 = new javax.swing.JLabel();
        i59 = new javax.swing.JLabel();
        i60 = new javax.swing.JLabel();
        i61 = new javax.swing.JLabel();
        i62 = new javax.swing.JLabel();
        i63 = new javax.swing.JLabel();
        i64 = new javax.swing.JLabel();
        i65 = new javax.swing.JLabel();
        i66 = new javax.swing.JLabel();
        i67 = new javax.swing.JLabel();
        i68 = new javax.swing.JLabel();
        i69 = new javax.swing.JLabel();
        i70 = new javax.swing.JLabel();
        i71 = new javax.swing.JLabel();
        i72 = new javax.swing.JLabel();
        i73 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        userListTextArea1 = new javax.swing.JTextArea();

        userListTextArea.setEditable(false);
        userListTextArea.setBackground(new java.awt.Color(240, 240, 240));
        userListTextArea.setColumns(20);
        userListTextArea.setRows(5);
        jScrollPane2.setViewportView(userListTextArea);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(219, 109, 252));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(194, 181, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(194, 181, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 87, 169)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 36)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 153, 153));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Nickname");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 40));

        sendButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sendButton.setForeground(new java.awt.Color(55, 178, 204));
        sendButton.setText("Send");
        sendButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(55, 178, 204)));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 110, 40));

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(55, 178, 204));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(55, 178, 204)));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 30));
        jPanel1.add(chatInputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 230, 40));

        chatListTextArea.setEditable(false);
        chatListTextArea.setContentType("text/html"); // NOI18N
        chatListTextArea.setText("");
        jScrollPane3.setViewportView(chatListTextArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 590));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, 370, 700));

        jPanel3.setBackground(new java.awt.Color(194, 181, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 87, 169)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Usuarios");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 40));

        userListTextArea2.setEditable(false);
        userListTextArea2.setColumns(20);
        userListTextArea2.setRows(5);
        jScrollPane5.setViewportView(userListTextArea2);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 640));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 700));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 87, 169)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        i0.setBackground(new java.awt.Color(255, 255, 255));
        i0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        i2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 50, 50));

        i3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 50));

        i4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 50));

        i5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 50));

        i6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 50));

        i7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, 50));

        i8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 50));

        i9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 50, 50));

        i10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 50, 50));

        i11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 50));

        i12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 50, 50));

        i13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, 50));

        i14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 50, 50));

        i15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 50, 50));

        i16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 50));

        i17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 50, 50));

        i18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 50, 50));

        i19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 50, 50));

        i20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 50, 50));

        i21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 50));

        i22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 50, 50));

        i23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 50, 50));

        i24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 50, 50));

        i25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 50, 50));

        i26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 50, 50));

        i27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 50, 50));

        i28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 50, 50));

        i29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 50, 50));

        i30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 50, 50));

        i31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 50, 50));

        i32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 50, 50));

        i33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 50, 50));

        i34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 50, 50));

        i35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, 50));

        i36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 50));

        i37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, 50));

        i38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 50, 50));

        i39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, 50));

        i40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 50, 50));

        i41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i41, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 50, 50));

        i42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i42, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 50, 50));

        i43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i43, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 50, 50));

        i44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 50, 50));

        i45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 50, 50));

        i46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 50, 50));

        i47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i47, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 50, 50));

        i48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i48, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 50, 50));

        i49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i49, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 50, 50));

        i50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 70, 70));

        i51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 70, 70));

        i52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 70, 70));

        i53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 70, 70));

        i54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i54, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 70, 70));

        i55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i55, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 70));

        i56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i56, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 70, 70));

        i57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i57, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 70, 70));

        i58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 70, 70));

        i59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i59, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 70, 70));

        i60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i60, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 70, 70));

        i61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i61, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 70, 70));

        i62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i62, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 70, 70));

        i63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i63, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 70, 70));

        i64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i64, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 70, 70));

        i65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i65, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 70, 70));

        i66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i66, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 70, 70));

        i67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i67, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 70, 70));

        i68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i68, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 70, 70));

        i69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i69, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 70, 70));

        i70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i70, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 70, 70));

        i71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i71, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 70, 70));

        i72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i72, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 70, 70));

        i73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(i73, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 70, 70));

        userListTextArea1.setEditable(false);
        userListTextArea1.setBackground(new java.awt.Color(194, 181, 252));
        userListTextArea1.setColumns(20);
        userListTextArea1.setRows(5);
        jScrollPane4.setViewportView(userListTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        sendNewMessage();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        try {
            chat.logout(username);  //use the reference "chat" to call remote methods
            System.exit(0);
            //catch the exceptions may occur, Rubbish URL, RemoteException
        } catch (RemoteException ex) {
            Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatInputText;
    private javax.swing.JTextPane chatListTextArea;
    private javax.swing.JLabel i0;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i10;
    private javax.swing.JLabel i11;
    private javax.swing.JLabel i12;
    private javax.swing.JLabel i13;
    private javax.swing.JLabel i14;
    private javax.swing.JLabel i15;
    private javax.swing.JLabel i16;
    private javax.swing.JLabel i17;
    private javax.swing.JLabel i18;
    private javax.swing.JLabel i19;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel i20;
    private javax.swing.JLabel i21;
    private javax.swing.JLabel i22;
    private javax.swing.JLabel i23;
    private javax.swing.JLabel i24;
    private javax.swing.JLabel i25;
    private javax.swing.JLabel i26;
    private javax.swing.JLabel i27;
    private javax.swing.JLabel i28;
    private javax.swing.JLabel i29;
    private javax.swing.JLabel i3;
    private javax.swing.JLabel i30;
    private javax.swing.JLabel i31;
    private javax.swing.JLabel i32;
    private javax.swing.JLabel i33;
    private javax.swing.JLabel i34;
    private javax.swing.JLabel i35;
    private javax.swing.JLabel i36;
    private javax.swing.JLabel i37;
    private javax.swing.JLabel i38;
    private javax.swing.JLabel i39;
    private javax.swing.JLabel i4;
    private javax.swing.JLabel i40;
    private javax.swing.JLabel i41;
    private javax.swing.JLabel i42;
    private javax.swing.JLabel i43;
    private javax.swing.JLabel i44;
    private javax.swing.JLabel i45;
    private javax.swing.JLabel i46;
    private javax.swing.JLabel i47;
    private javax.swing.JLabel i48;
    private javax.swing.JLabel i49;
    private javax.swing.JLabel i5;
    private javax.swing.JLabel i50;
    private javax.swing.JLabel i51;
    private javax.swing.JLabel i52;
    private javax.swing.JLabel i53;
    private javax.swing.JLabel i54;
    private javax.swing.JLabel i55;
    private javax.swing.JLabel i56;
    private javax.swing.JLabel i57;
    private javax.swing.JLabel i58;
    private javax.swing.JLabel i59;
    private javax.swing.JLabel i6;
    private javax.swing.JLabel i60;
    private javax.swing.JLabel i61;
    private javax.swing.JLabel i62;
    private javax.swing.JLabel i63;
    private javax.swing.JLabel i64;
    private javax.swing.JLabel i65;
    private javax.swing.JLabel i66;
    private javax.swing.JLabel i67;
    private javax.swing.JLabel i68;
    private javax.swing.JLabel i69;
    private javax.swing.JLabel i7;
    private javax.swing.JLabel i70;
    private javax.swing.JLabel i71;
    private javax.swing.JLabel i72;
    private javax.swing.JLabel i73;
    private javax.swing.JLabel i8;
    private javax.swing.JLabel i9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea userListTextArea;
    private javax.swing.JTextArea userListTextArea1;
    private javax.swing.JTextArea userListTextArea2;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        userListTextArea.setLineWrap(true);     // to remove horizontal scrolling bar 
        setTitle("Chat Público");  
        setImages();
        addListeners();      
        this.nameLabel.setText(username);
        this.setVisible(true);
        setLocationRelativeTo(null);            // to visible the GUI in the middle of the screen
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    refresh();                  // this thread is used to refresh the chat window by every second 
                    try {                       // to display whole chat list
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        t1.start();
    }

    public void displayChatList() throws RemoteException {
        chatListTextArea.setText("");
        msgs = chat.getAllMessages();
        String doc = "<html><body><table>";
        for (Message m : msgs) {
            if (!((m.getUsername().equals(username)) && (m.getType().equals("join")))) {             
                String smileyName = m.getSmiley();               
                Date date = m.getDate();
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String a = dateFormat.format(date);
                SimpleDateFormat parseFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                SimpleDateFormat printFormat = new SimpleDateFormat("HH:mm:ss");
                try {
                    Date time = parseFormat.parse(a);
                    if (smileyName == null) {
                        doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getUsername() 
                                + "</b></font></td><td> " 
                                + m.getMsg() 
                                + "</td></tr>";
                    } else {                  
                        doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getUsername()  
                                + "</b></font></td><td><img src= '" 
                                + this.getClass().getResource("/images/"+smileyName) 
                                + "' width=50 height=50 /> </td></tr>";
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
                }                        
            }
        }
        doc += "</table></body></html>";
        chatListTextArea.setText(doc);
    }

    private void displayUserList() throws RemoteException {
        userListTextArea.setText("");
        users = chat.getAllUsers();
        for (String u : users) {
            if (!u.equals(username)) {             
                userListTextArea.append(" " + u + "\n");             
            }
        }
    }

    public void refresh() {
        try {
            displayChatList();
            displayUserList();
        } catch (RemoteException ex) {
            Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setImages() {
        ImageIcon icons[] = new ImageIcon[74];
        for (int i = 0; i < 50; i++) {
            icons[i] = new ImageIcon(getClass().getResource("/images/" + i + ".png"));
        }
        for (int i = 50; i < 74; i++) {
            icons[i] = new ImageIcon(getClass().getResource("/images/" + i + ".gif"));
        }
        i0.setIcon(icons[0]);
        i1.setIcon(icons[1]);
        i2.setIcon(icons[2]);
        i3.setIcon(icons[3]);
        i4.setIcon(icons[4]);
        i5.setIcon(icons[5]);
        i6.setIcon(icons[6]);
        i7.setIcon(icons[7]);
        i8.setIcon(icons[8]);
        i9.setIcon(icons[9]);
        i10.setIcon(icons[10]);
        i11.setIcon(icons[11]);
        i12.setIcon(icons[12]);
        i13.setIcon(icons[13]);
        i14.setIcon(icons[14]);
        i15.setIcon(icons[15]);
        i16.setIcon(icons[16]);
        i17.setIcon(icons[17]);
        i18.setIcon(icons[18]);
        i19.setIcon(icons[19]);
        i20.setIcon(icons[20]);
        i21.setIcon(icons[21]);
        i22.setIcon(icons[22]);
        i23.setIcon(icons[23]);
        i24.setIcon(icons[24]);
        i25.setIcon(icons[25]);
        i26.setIcon(icons[26]);
        i27.setIcon(icons[27]);
        i28.setIcon(icons[28]);
        i29.setIcon(icons[29]);
        i30.setIcon(icons[30]);
        i31.setIcon(icons[31]);
        i32.setIcon(icons[32]);
        i33.setIcon(icons[33]);
        i34.setIcon(icons[34]);
        i35.setIcon(icons[35]);
        i36.setIcon(icons[36]);
        i37.setIcon(icons[37]);
        i38.setIcon(icons[38]);
        i39.setIcon(icons[39]);
        i40.setIcon(icons[40]);
        i41.setIcon(icons[41]);
        i42.setIcon(icons[42]);
        i43.setIcon(icons[43]);
        i44.setIcon(icons[44]);
        i45.setIcon(icons[45]);
        i46.setIcon(icons[46]);
        i47.setIcon(icons[47]);
        i48.setIcon(icons[48]);
        i49.setIcon(icons[49]);
        i50.setIcon(icons[50]);
        i51.setIcon(icons[51]);
        i52.setIcon(icons[52]);
        i53.setIcon(icons[53]);
        i54.setIcon(icons[54]);
        i55.setIcon(icons[55]);
        i56.setIcon(icons[56]);
        i57.setIcon(icons[57]);
        i58.setIcon(icons[58]);
        i59.setIcon(icons[59]);
        i60.setIcon(icons[60]);
        i61.setIcon(icons[61]);
        i62.setIcon(icons[62]);
        i63.setIcon(icons[63]);
        i64.setIcon(icons[64]);
        i65.setIcon(icons[65]);
        i66.setIcon(icons[66]);
        i67.setIcon(icons[67]);
        i68.setIcon(icons[68]);
        i69.setIcon(icons[69]);
        i70.setIcon(icons[70]);
        i71.setIcon(icons[71]);
        i72.setIcon(icons[72]);
        i73.setIcon(icons[73]);
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        Message message = new Message();
        message.setUsername(username);
        message.setType("client");
        message.setDate(new Date());
        if (e.getSource() == i0) {
            message.setSmiley("0.png");
        } else if (e.getSource() == i1) {
            message.setSmiley("1.png");
        } else if (e.getSource() == i2) {
            message.setSmiley("2.png");
        } else if (e.getSource() == i3) {
            message.setSmiley("3.png");
        } else if (e.getSource() == i5) {
            message.setSmiley("4.png");
        } else if (e.getSource() == i4) {
            message.setSmiley("5.png");
        } else if (e.getSource() == i6) {
            message.setSmiley("6.png");
        } else if (e.getSource() == i7) {
            message.setSmiley("7.png");
        } else if (e.getSource() == i8) {
            message.setSmiley("8.png");
        } else if (e.getSource() == i9) {
            message.setSmiley("9.png");
        } else if (e.getSource() == i10) {
            message.setSmiley("10.png");
        } else if (e.getSource() == i11) {
            message.setSmiley("11.png");
        } else if (e.getSource() == i12) {
            message.setSmiley("12.png");
        } else if (e.getSource() == i13) {
            message.setSmiley("13.png");
        } else if (e.getSource() == i14) {
            message.setSmiley("14.png");
        } else if (e.getSource() == i15) {
            message.setSmiley("15.png");
        } else if (e.getSource() == i16) {
            message.setSmiley("16.png");
        } else if (e.getSource() == i17) {
            message.setSmiley("17.png");
        } else if (e.getSource() == i18) {
            message.setSmiley("18.png");
        } else if (e.getSource() == i19) {
            message.setSmiley("19.png");
        } else if (e.getSource() == i20) {
            message.setSmiley("20.png");
        } else if (e.getSource() == i21) {
            message.setSmiley("21.png");
        } else if (e.getSource() == i22) {
            message.setSmiley("22.png");
        } else if (e.getSource() == i23) {
            message.setSmiley("23.png");
        } else if (e.getSource() == i24) {
            message.setSmiley("24.png");
        } else if (e.getSource() == i25) {
            message.setSmiley("25.png");
        } else if (e.getSource() == i26) {
            message.setSmiley("26.png");
        } else if (e.getSource() == i27) {
            message.setSmiley("27.png");
        } else if (e.getSource() == i28) {
            message.setSmiley("28.png");
        } else if (e.getSource() == i29) {
            message.setSmiley("29.png");
        } else if (e.getSource() == i30) {
            message.setSmiley("30.png");
        } else if (e.getSource() == i31) {
            message.setSmiley("31.png");
        } else if (e.getSource() == i32) {
            message.setSmiley("32.png");
        } else if (e.getSource() == i33) {
            message.setSmiley("33.png");
        } else if (e.getSource() == i34) {
            message.setSmiley("34.png");
        } else if (e.getSource() == i35) {
            message.setSmiley("35.png");
        } else if (e.getSource() == i36) {
            message.setSmiley("36.png");
        } else if (e.getSource() == i37) {
            message.setSmiley("37.png");
        } else if (e.getSource() == i38) {
            message.setSmiley("38.png");
        } else if (e.getSource() == i39) {
            message.setSmiley("39.png");
        } else if (e.getSource() == i40) {
            message.setSmiley("40.png");
        } else if (e.getSource() == i41) {
            message.setSmiley("41.png");
        } else if (e.getSource() == i42) {
            message.setSmiley("42.png");
        } else if (e.getSource() == i43) {
            message.setSmiley("43.png");
        } else if (e.getSource() == i44) {
            message.setSmiley("44.png");
        } else if (e.getSource() == i45) {
            message.setSmiley("45.png");
        } else if (e.getSource() == i46) {
            message.setSmiley("46.png");
        } else if (e.getSource() == i47) {
            message.setSmiley("47.png");
        } else if (e.getSource() == i48) {
            message.setSmiley("48.png");
        } else if (e.getSource() == i49) {
            message.setSmiley("49.png");
        } else if (e.getSource() == i50) {
            message.setSmiley("50.gif");
        } else if (e.getSource() == i51) {
            message.setSmiley("51.gif");
        } else if (e.getSource() == i52) {
            message.setSmiley("52.gif");
        } else if (e.getSource() == i53) {
            message.setSmiley("53.gif");
        } else if (e.getSource() == i54) {
            message.setSmiley("54.gif");
        } else if (e.getSource() == i55) {
            message.setSmiley("55.gif");
        } else if (e.getSource() == i56) {
            message.setSmiley("56.gif");
        } else if (e.getSource() == i57) {
            message.setSmiley("57.gif");
        } else if (e.getSource() == i58) {
            message.setSmiley("58.gif");
        } else if (e.getSource() == i59) {
            message.setSmiley("59.gif");
        } else if (e.getSource() == i60) {
            message.setSmiley("60.gif");
        } else if (e.getSource() == i61) {
            message.setSmiley("61.gif");
        } else if (e.getSource() == i62) {
            message.setSmiley("62.gif");
        } else if (e.getSource() == i63) {
            message.setSmiley("63.gif");
        } else if (e.getSource() == i64) {
            message.setSmiley("64.gif");
        } else if (e.getSource() == i65) {
            message.setSmiley("65.gif");
        } else if (e.getSource() == i66) {
            message.setSmiley("66.gif");
        } else if (e.getSource() == i67) {
            message.setSmiley("67.gif");
        } else if (e.getSource() == i68) {
            message.setSmiley("68.gif");
        } else if (e.getSource() == i69) {
            message.setSmiley("69.gif");
        } else if (e.getSource() == i70) {
            message.setSmiley("70.gif");
        } else if (e.getSource() == i71) {
            message.setSmiley("71.gif");
        } else if (e.getSource() == i72) {
            message.setSmiley("72.gif");
        } else if (e.getSource() == i73) {
            message.setSmiley("73.gif");
        } 
        try {
            chat.sendMessage(message);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    private void addListeners() {
         i0.addMouseListener(this);
         i1.addMouseListener(this);
         i2.addMouseListener(this);
         i3.addMouseListener(this);
         i4.addMouseListener(this);
         i5.addMouseListener(this);
         i6.addMouseListener(this);
         i7.addMouseListener(this);
         i8.addMouseListener(this);
         i9.addMouseListener(this);
         i10.addMouseListener(this);
         i11.addMouseListener(this);
         i12.addMouseListener(this);
         i13.addMouseListener(this);
         i14.addMouseListener(this);
         i15.addMouseListener(this);
         i16.addMouseListener(this);
         i17.addMouseListener(this);
         i18.addMouseListener(this);
         i19.addMouseListener(this);
         i20.addMouseListener(this);
         i21.addMouseListener(this);
         i22.addMouseListener(this);
         i23.addMouseListener(this);
         i24.addMouseListener(this);
         i25.addMouseListener(this);
         i26.addMouseListener(this);
         i27.addMouseListener(this);
         i28.addMouseListener(this);
         i29.addMouseListener(this);
         i30.addMouseListener(this);
         i31.addMouseListener(this);
         i32.addMouseListener(this);
         i33.addMouseListener(this);
         i34.addMouseListener(this);
         i35.addMouseListener(this);
         i36.addMouseListener(this);
         i37.addMouseListener(this);
         i38.addMouseListener(this);
         i39.addMouseListener(this);
         i40.addMouseListener(this);
         i41.addMouseListener(this);
         i42.addMouseListener(this);
         i43.addMouseListener(this);
         i44.addMouseListener(this);
         i45.addMouseListener(this);
         i46.addMouseListener(this);
         i47.addMouseListener(this);
         i48.addMouseListener(this);
         i49.addMouseListener(this);
         i50.addMouseListener(this);
         i51.addMouseListener(this);
         i52.addMouseListener(this);
         i53.addMouseListener(this);
         i54.addMouseListener(this);
         i55.addMouseListener(this);
         i56.addMouseListener(this);
         i57.addMouseListener(this);
         i58.addMouseListener(this);
         i59.addMouseListener(this);
         i60.addMouseListener(this);
         i61.addMouseListener(this);
         i62.addMouseListener(this);
         i63.addMouseListener(this);
         i64.addMouseListener(this);
         i65.addMouseListener(this);
         i66.addMouseListener(this);
         i67.addMouseListener(this);
         i68.addMouseListener(this);
         i69.addMouseListener(this);
         i70.addMouseListener(this);
         i71.addMouseListener(this);
         i72.addMouseListener(this);
         i73.addMouseListener(this);
         chatInputText.addKeyListener(this);
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            sendNewMessage();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    private void sendNewMessage() {
        String inputMessage = chatInputText.getText();
        chatInputText.setText("");
        Message message = new Message();
        message.setUsername(username);
        message.setMsg(inputMessage);
        message.setType("client");
        message.setDate(new Date());
        try {
            chat.sendMessage(message);
        } catch (RemoteException ex) {
            Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
